import assert from 'node:assert/strict';
import 'fake-indexeddb/auto';
import ts from 'typescript';
import {readFile} from 'node:fs/promises';
const url=new URL('../lib/local-store.ts',import.meta.url);
let source=await readFile(url,'utf8');
source=source.replace("'zod'",JSON.stringify(new URL('../node_modules/zod/index.js',import.meta.url).href)).replace("'./catalog'",JSON.stringify(new URL('../lib/catalog.ts',import.meta.url).href)).replace("'./coffee-guide'",JSON.stringify(new URL('../lib/coffee-guide.ts',import.meta.url).href));
const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
const {localApi,importBackup,backupSchema}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
const request=(method,body)=>localApi('/api/journal',{method,body:JSON.stringify(body)});
let initial=await localApi('/api/journal');assert.equal(initial.beans.length,14);assert.ok(initial.beans.every(b=>b.catalogId&&b.roastDate===''));const starterId=initial.beans[0].id;await request('DELETE',{kind:'bean',id:starterId});assert.equal((await localApi('/api/journal')).beans.length,13);assert.equal((await localApi('/api/journal')).beans.length,13);
const base={name:'测试豆',roaster:'Test',origin:'China',process:'水洗',roast:'浅烘焙',flavor:'桃子',status:'未开封',rating:0,repurchase:false,photo:'',roastDate:'',notes:''};
const {id}=await request('POST',{kind:'bean',data:base,saveToCatalog:true});
let state=await localApi('/api/journal');assert.equal(state.beans.length,14);assert.equal(state.catalog.length,15);assert.ok(state.beans[0].catalogId);
await request('POST',{kind:'brew',data:{beanId:id,date:'2026-10-02',dose:15,water:225,temp:92,grind:'中细',time:'2:30',notes:'好喝',rating:4}});
state=await localApi('/api/journal');const backup={format:'beanlet',version:1,beans:state.beans,catalog:state.catalog.filter(b=>!b.id.startsWith('hydrangea-')),brews:state.brews};
assert.equal(await importBackup(new File([JSON.stringify(backup)],'backup.json')),0);
const photo='data:image/png;base64,aGVsbG8=';
const imported={...backup,beans:[{...base,id:'photo-bean',photo}],catalog:[],brews:[]};
assert.equal(await importBackup(new File([JSON.stringify(imported)],'backup.json')),1);
state=await localApi('/api/journal');assert.equal(state.beans.find(b=>b.id==='photo-bean').photo,photo);
await assert.rejects(importBackup(new File(['{}'],'bad.json')));
assert.throws(()=>backupSchema.parse({...backup,brews:[{...backup.brews[0],beanId:'missing'}]}));
await request('DELETE',{kind:'bean',id});state=await localApi('/api/journal');assert.equal(state.brews.length,0);assert.equal(state.beans.length,14);
await assert.rejects(request('POST',{kind:'bean',data:{...base,roast:''}}));
console.log('Local storage: save, catalog, brew, photo backup, merge, invalid import and cascading delete passed');
