import assert from 'node:assert/strict';
import 'fake-indexeddb/auto';
import ts from 'typescript';
import {readFile} from 'node:fs/promises';
const url=new URL('../lib/local-store.ts',import.meta.url);
let source=await readFile(url,'utf8');
source=source.replace("'./tasted'",JSON.stringify(new URL('../lib/tasted.ts',import.meta.url).href));
source=source.replace("'zod'",JSON.stringify(new URL('../node_modules/zod/index.js',import.meta.url).href)).replace("'./catalog'",JSON.stringify(new URL('../lib/catalog.ts',import.meta.url).href)).replace("'./coffee-guide'",JSON.stringify(new URL('../lib/coffee-guide.ts',import.meta.url).href));
const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
const {localApi,importBackup,backupSchema,migrateStarters}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
const request=(method,body)=>localApi('/api/journal',{method,body:JSON.stringify(body)});
let initial=await localApi('/api/journal');assert.equal(initial.beans.length,0);assert.equal(initial.catalog.length,14);assert.equal((await localApi('/api/journal')).beans.length,0);
const starters=initial.catalog.map(b=>({...b,id:'starter-'+b.id,catalogId:b.id,recordType:'bean',status:'未开封',useOriginalArt:true}));
const old={format:'beanlet',version:1,beans:starters,catalog:[],brews:[]};
assert.equal(migrateStarters(old).beans.length,0);
const edited={...old,beans:starters.map((b,i)=>i===0?{...b,notes:'我的笔记'}:b),brews:[{beanId:starters[1].id}]};
const migrated=migrateStarters(edited);assert.equal(migrated.beans.length,2);assert.equal(migrated.beans[0].notes,'我的笔记');assert.equal(migrated.beans[1].id,starters[1].id);assert.equal(migrateStarters(migrated),migrated);
const base={name:'测试豆',roaster:'Test',origin:'China',process:'水洗',roast:'浅烘焙',flavor:'桃子',status:'未开封',rating:0,repurchase:false,photo:'',roastDate:'',notes:''};
const {id}=await request('POST',{kind:'bean',data:base,saveToCatalog:true});
let state=await localApi('/api/journal');assert.equal(state.beans.length,1);assert.equal(state.catalog.length,15);assert.ok(state.beans[0].catalogId);
await request('POST',{kind:'brew',data:{beanId:id,date:'2026-10-02',dose:15,water:225,temp:92,grind:'中细',time:'2:30',notes:'好喝',rating:4}});
state=await localApi('/api/journal');const backup={format:'beanlet',version:1,beans:state.beans,catalog:state.catalog.filter(b=>!b.id.startsWith('hydrangea-')),brews:state.brews};
assert.equal(await importBackup(new File([JSON.stringify(backup)],'backup.json')),0);
const photo='data:image/png;base64,aGVsbG8=';
const imported={...backup,beans:[{...base,id:'photo-bean',photo}],catalog:[],brews:[]};
assert.equal(await importBackup(new File([JSON.stringify(imported)],'backup.json')),1);
state=await localApi('/api/journal');assert.equal(state.beans.find(b=>b.id==='photo-bean').photo,photo);
await assert.rejects(importBackup(new File(['{}'],'bad.json')));
assert.throws(()=>backupSchema.parse({...backup,brews:[{...backup.brews[0],beanId:'missing'}]}));
await request('DELETE',{kind:'bean',id});state=await localApi('/api/journal');assert.equal(state.brews.length,0);assert.equal(state.beans.length,1);
await assert.rejects(request('POST',{kind:'bean',data:{...base,roast:''}}));
console.log('Local storage: save, catalog, brew, photo backup, merge, invalid import and cascading delete passed');

const before=(await localApi('/api/journal')).beans.length;
await request('POST',{kind:'taste',data:initial.catalog[0]});
state=await localApi('/api/journal');assert.equal(state.beans.length,before);assert.ok(state.tasted.some(x=>x.id===initial.catalog[0].id));
await request('POST',{kind:'taste',data:initial.catalog[0]});assert.equal((await localApi('/api/journal')).tasted.filter(x=>x.id===initial.catalog[0].id).length,1);
await request('DELETE',{kind:'taste',id:initial.catalog[0].id});assert.ok(!(await localApi('/api/journal')).tasted.some(x=>x.id===initial.catalog[0].id));
assert.ok(state.tasted.some(x=>x.bean.name==='测试豆'),'brew memory survives deletion');
const importedTaste={format:'beanlet',version:1,beans:[],catalog:[],brews:[],tasted:[{id:initial.catalog[2].id,bean:initial.catalog[2],firstDate:'',manual:true}]};
assert.equal(await importBackup(new File([JSON.stringify(importedTaste)],'taste.json')),1);
assert.equal(await importBackup(new File([JSON.stringify(importedTaste)],'taste.json')),0);
console.log('Tasted storage: manual marking, undo, deduplication, persistent memory and backup passed');

const favoriteId=initial.catalog[4].id;
await request('POST',{kind:'favorite',id:favoriteId});
assert.ok((await localApi('/api/journal')).favorites.includes(favoriteId));
await request('POST',{kind:'favorite',id:favoriteId});
assert.ok(!(await localApi('/api/journal')).favorites.includes(favoriteId));
const favoriteBackup={format:'beanlet',version:1,beans:[],catalog:[],brews:[],favorites:[favoriteId]};
assert.equal(await importBackup(new File([JSON.stringify(favoriteBackup)],'favorites.json')),1);
assert.equal(await importBackup(new File([JSON.stringify(favoriteBackup)],'favorites.json')),0);
const oldFavorite={format:'beanlet',version:1,beans:[{...base,id:'old-favorite',repurchase:true}],catalog:[],brews:[]};
await importBackup(new File([JSON.stringify(oldFavorite)],'legacy.json'));
assert.ok((await localApi('/api/journal')).favorites.includes('old-favorite'));
await request('POST',{kind:'favorite',id:'old-favorite'});
assert.ok(!(await localApi('/api/journal')).favorites.includes('old-favorite'),'old repurchase does not restore removed heart');
console.log('Favorites: toggle, reload, backup merge and legacy import passed');

const coffee=initial.catalog[6];
const {id:keptBag}=await request('POST',{kind:'bean',data:{...coffee,catalogId:coffee.id,recordType:'bean'}});
await request('POST',{kind:'brew',data:{beanId:keptBag,date:'2026-10-02',dose:15,water:240,temp:92,grind:'',time:'',notes:'',rating:4}});
await request('DELETE',{kind:'catalog',id:coffee.id});
state=await localApi('/api/journal');
assert.ok(!state.catalog.some(b=>b.id===coffee.id));
assert.ok(state.beans.some(b=>b.id===keptBag));
assert.ok(state.brews.some(b=>b.beanId===keptBag));
assert.ok(state.tasted.some(b=>b.id===coffee.id));
assert.ok(backupSchema.parse(state).hiddenCatalog.includes(coffee.id));
const hiddenBackup={format:'beanlet',version:1,beans:[],catalog:[],brews:[],hiddenCatalog:[initial.catalog[7].id]};
await importBackup(new File([JSON.stringify(hiddenBackup)],'hidden.json'));
assert.ok(!(await localApi('/api/journal')).catalog.some(b=>b.id===initial.catalog[7].id));
const custom=(await localApi('/api/journal')).catalog.find(b=>!b.id.startsWith('hydrangea-'));
await request('DELETE',{kind:'catalog',id:custom.id});
assert.ok(!(await localApi('/api/journal')).catalog.some(b=>b.id===custom.id));
console.log('Catalog removal: built-in/custom, retained bags/brews/memories, reload and backup passed');
