import assert from 'node:assert/strict';
import 'fake-indexeddb/auto';
import ts from 'typescript';
import {readFile} from 'node:fs/promises';
const url=new URL('../lib/local-store.ts',import.meta.url);
let source=await readFile(url,'utf8');
source=source.replace("'./bean-stock'",JSON.stringify(new URL('../lib/bean-stock.ts',import.meta.url).href));
source=source.replace("'./tasted'",JSON.stringify(new URL('../lib/tasted.ts',import.meta.url).href));
source=source.replace("'zod'",JSON.stringify(new URL('../node_modules/zod/index.js',import.meta.url).href)).replace("'./catalog'",JSON.stringify(new URL('../lib/catalog.ts',import.meta.url).href)).replace("'./coffee-guide'",JSON.stringify(new URL('../lib/coffee-guide.ts',import.meta.url).href));
const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
const {localApi,importBackup,exportBackup,backupSchema,migrateStarters}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
const request=(method,body)=>localApi('/api/journal',{method,body:JSON.stringify(body)});
let initial=await localApi('/api/journal');assert.equal(initial.beans.length,0);assert.equal(initial.catalog.length,14);assert.equal((await localApi('/api/journal')).beans.length,0);
const starters=initial.catalog.map(b=>({...b,id:'starter-'+b.id,catalogId:b.id,recordType:'bean',status:'未开封',useOriginalArt:true}));
const old={format:'beanlet',version:1,beans:starters,catalog:[],brews:[]};
assert.equal(migrateStarters(old).beans.length,0);
const edited={...old,beans:starters.map((b,i)=>i===0?{...b,notes:'我的笔记'}:b),brews:[{beanId:starters[1].id}]};
const migrated=migrateStarters(edited);assert.equal(migrated.beans.length,2);assert.equal(migrated.beans[0].notes,'我的笔记');assert.equal(migrated.beans[1].id,starters[1].id);assert.equal(migrateStarters(migrated),migrated);
const base={name:'测试豆',roaster:'Test',origin:'China',process:'水洗',roast:'浅烘焙',flavor:'桃子',status:'未开封',rating:0,repurchase:false,photo:'',roastDate:'',notes:''};
const {id}=await request('POST',{kind:'bean',data:base,saveToCatalog:true});
let state=await localApi('/api/journal');assert.equal(state.beans.length,1);assert.equal(state.catalog.length,15);assert.ok(state.beans[0].catalogId);
await request('POST',{kind:'brew',data:{beanId:id,date:'2026-10-02',dose:15,water:225,temp:92,grind:'中细',time:'2:30',notes:'好喝',rating:4}});
state=await localApi('/api/journal');const backup={format:'beanlet',version:1,beans:state.beans,catalog:state.catalog.filter(b=>!b.id.startsWith('hydrangea-')),brews:state.brews};
assert.equal(await importBackup(new File([JSON.stringify(backup)],'backup.json')),0);
const photo='data:image/png;base64,aGVsbG8=';
const imported={...backup,beans:[{...base,id:'photo-bean',photo}],catalog:[],brews:[]};
assert.equal(await importBackup(new File([JSON.stringify(imported)],'backup.json')),1);
state=await localApi('/api/journal');assert.equal(state.beans.find(b=>b.id==='photo-bean').photo,photo);
await assert.rejects(importBackup(new File(['{}'],'bad.json')));
assert.throws(()=>backupSchema.parse({...backup,brews:[{...backup.brews[0],beanId:'missing'}]}));
await request('DELETE',{kind:'bean',id});state=await localApi('/api/journal');assert.equal(state.brews.length,0);assert.equal(state.beans.length,1);
await assert.rejects(request('POST',{kind:'bean',data:{...base,roast:''}}));
console.log('Local storage: save, catalog, brew, photo backup, merge, invalid import and cascading delete passed');

const before=(await localApi('/api/journal')).beans.length;
await request('POST',{kind:'taste',data:initial.catalog[0]});
state=await localApi('/api/journal');assert.equal(state.beans.length,before);assert.ok(state.tasted.some(x=>x.id===initial.catalog[0].id));
await request('POST',{kind:'taste',data:initial.catalog[0]});assert.equal((await localApi('/api/journal')).tasted.filter(x=>x.id===initial.catalog[0].id).length,1);
await request('DELETE',{kind:'taste',id:initial.catalog[0].id});assert.ok(!(await localApi('/api/journal')).tasted.some(x=>x.id===initial.catalog[0].id));
assert.ok(state.tasted.some(x=>x.bean.name==='测试豆'),'brew memory survives deletion');
const importedTaste={format:'beanlet',version:1,beans:[],catalog:[],brews:[],tasted:[{id:initial.catalog[2].id,bean:initial.catalog[2],firstDate:'',manual:true}]};
assert.equal(await importBackup(new File([JSON.stringify(importedTaste)],'taste.json')),1);
assert.equal(await importBackup(new File([JSON.stringify(importedTaste)],'taste.json')),0);
console.log('Tasted storage: manual marking, undo, deduplication, persistent memory and backup passed');

const favoriteId=initial.catalog[4].id;
await request('POST',{kind:'favorite',id:favoriteId});
assert.ok((await localApi('/api/journal')).favorites.includes(favoriteId));
await request('POST',{kind:'favorite',id:favoriteId});
assert.ok(!(await localApi('/api/journal')).favorites.includes(favoriteId));
const favoriteBackup={format:'beanlet',version:1,beans:[],catalog:[],brews:[],favorites:[favoriteId]};
assert.equal(await importBackup(new File([JSON.stringify(favoriteBackup)],'favorites.json')),1);
assert.equal(await importBackup(new File([JSON.stringify(favoriteBackup)],'favorites.json')),0);
const oldFavorite={format:'beanlet',version:1,beans:[{...base,id:'old-favorite',repurchase:true}],catalog:[],brews:[]};
await importBackup(new File([JSON.stringify(oldFavorite)],'legacy.json'));
assert.ok((await localApi('/api/journal')).favorites.includes('old-favorite'));
await request('POST',{kind:'favorite',id:'old-favorite'});
assert.ok(!(await localApi('/api/journal')).favorites.includes('old-favorite'),'old repurchase does not restore removed heart');
console.log('Favorites: toggle, reload, backup merge and legacy import passed');

const coffee=initial.catalog[6];
const {id:keptBag}=await request('POST',{kind:'bean',data:{...coffee,catalogId:coffee.id,recordType:'bean'}});
await request('POST',{kind:'brew',data:{beanId:keptBag,date:'2026-10-02',dose:15,water:240,temp:92,grind:'',time:'',notes:'',rating:4}});
await request('DELETE',{kind:'catalog',id:coffee.id});
state=await localApi('/api/journal');
assert.ok(!state.catalog.some(b=>b.id===coffee.id));
assert.ok(state.beans.some(b=>b.id===keptBag));
assert.ok(state.brews.some(b=>b.beanId===keptBag));
assert.ok(state.tasted.some(b=>b.id===coffee.id));
assert.ok(backupSchema.parse(state).hiddenCatalog.includes(coffee.id));
const hiddenBackup={format:'beanlet',version:1,beans:[],catalog:[],brews:[],hiddenCatalog:[initial.catalog[7].id]};
await importBackup(new File([JSON.stringify(hiddenBackup)],'hidden.json'));
assert.ok(!(await localApi('/api/journal')).catalog.some(b=>b.id===initial.catalog[7].id));
const custom=(await localApi('/api/journal')).catalog.find(b=>!b.id.startsWith('hydrangea-'));
await request('DELETE',{kind:'catalog',id:custom.id});
assert.ok(!(await localApi('/api/journal')).catalog.some(b=>b.id===custom.id));
console.log('Catalog removal: built-in/custom, retained bags/brews/memories, reload and backup passed');

const bilingualId=(await request('POST',{kind:'bean',data:{...base,name:'天堂庄园',nameEn:'El Paraiso'},saveToCatalog:true})).id;
state=await localApi('/api/journal');
const bilingual=state.beans.find(b=>b.id===bilingualId);
assert.equal(bilingual.nameEn,'El Paraiso');
assert.equal(state.catalog.find(b=>b.id===bilingual.catalogId).nameEn,'El Paraiso');
assert.equal(backupSchema.parse(state).beans.find(b=>b.id===bilingualId).nameEn,'El Paraiso');
await request('PUT',{kind:'bean',id:bilingualId,data:{...bilingual,nameEn:''}});
assert.equal((await localApi('/api/journal')).beans.find(b=>b.id===bilingualId).nameEn,'');
console.log('Bilingual names: saved, catalog copy, backup and clearing passed');

const milkId=(await request('POST',{kind:'brew',data:{beanId:bilingualId,date:'2026-10-02',kind:'milk',dose:18,yield:36,milkAmount:150,milkType:'燕麦奶',serving:'冰',grind:'细',time:'0:28',notes:'',rating:0}})).id;
state=await localApi('/api/journal');
const milk=backupSchema.parse(state).brews.find(b=>b.id===milkId);
assert.equal(milk.kind,'milk');assert.equal(milk.yield,36);assert.equal(milk.milkAmount,150);assert.equal(milk.water,undefined);
assert.equal(backupSchema.parse({...state,brews:[{id:'legacy',beanId:bilingualId,date:'2026-10-02',dose:15,water:225,temp:92,grind:'',time:'2:30',notes:'',rating:4}]}).brews[0].kind,'pourOver');
await request('POST',{kind:'brew',data:{beanId:bilingualId,date:'2026-10-02',kind:'milk',dose:18,grind:'',time:'',notes:'',rating:0}});
await assert.rejects(request('POST',{kind:'brew',data:{beanId:bilingualId,date:'2026-10-02',kind:'milk',dose:18,milkAmount:-1,grind:'',time:'',notes:'',rating:0}}));
console.log('Coffee types: legacy import, milk recipe, optional parameters and validation passed');

state=await localApi('/api/journal');
const countBeforeEdit=state.brews.length;
const original=state.brews.find(b=>b.id===milkId);
await request('PUT',{kind:'brew',id:milkId,data:{...original,date:'2026-10-01',kind:'pourOver',water:250,yield:undefined,milkAmount:undefined,milkType:undefined,serving:undefined,notes:'edited'}});
state=await localApi('/api/journal');
assert.equal(state.brews.length,countBeforeEdit);
assert.equal(state.brews.filter(b=>b.id===milkId).length,1);
assert.equal(state.brews.find(b=>b.id===milkId).date,'2026-10-01');
assert.equal(state.brews.find(b=>b.id===milkId).kind,'pourOver');
assert.equal(state.brews.find(b=>b.id===milkId).milkAmount,undefined);
await assert.rejects(request('PUT',{kind:'brew',id:'missing-record',data:original}));
assert.equal((await localApi('/api/journal')).brews.length,countBeforeEdit);
console.log('Coffee editing: update in place, date/type changes and missing record rejection passed');

for(const kind of ['pourOver','milk'])for(const dose of [undefined,0,-1,201]){
 await assert.rejects(request('POST',{kind:'brew',data:{beanId:bilingualId,date:'2026-10-02',kind,dose,grind:'',time:'',notes:'',rating:0}}),/粉量/);
}
await assert.rejects(request('PUT',{kind:'brew',id:milkId,data:{...original,dose:undefined}}),/粉量/);
assert.equal(backupSchema.parse({...state,brews:[{...original,dose:undefined}]}).brews[0].dose,undefined,'legacy backups can still omit dose');
console.log('Required dose: both types, edits, invalid values and legacy backup compatibility passed');

const stockBag=(await request('POST',{kind:'bean',saveToCatalog:true,data:{...base,weight:200}})).id;
const stockBrew=(await request('POST',{kind:'brew',data:{beanId:stockBag,date:'2026-10-02',dose:15,kind:'pourOver',grind:'',time:'',notes:'',rating:0}})).id;
await request('PUT',{kind:'stock',id:stockBag,remaining:170});
state=await localApi('/api/journal');
const stockBean=state.beans.find(b=>b.id===stockBag);
assert.equal(stockBean.stockAdjustment,-15);
assert.equal(state.catalog.find(b=>b.id===stockBean.catalogId).weight,undefined);
const {beanStock}=await import('../lib/bean-stock.ts');
assert.equal(beanStock(stockBean,state.brews).remaining,170);
await request('PUT',{kind:'brew',id:stockBrew,data:{...state.brews.find(b=>b.id===stockBrew),dose:20}});
state=await localApi('/api/journal');assert.equal(beanStock(stockBean,state.brews).remaining,165);
await request('DELETE',{kind:'brew',id:stockBrew});
state=await localApi('/api/journal');assert.equal(beanStock(stockBean,state.brews).remaining,185);
assert.equal(backupSchema.parse(state).beans.find(b=>b.id===stockBag).stockAdjustment,-15);
await assert.rejects(request('PUT',{kind:'stock',id:stockBag,remaining:201}));
await assert.rejects(request('PUT',{kind:'stock',id:stockBag,remaining:-1}));
console.log('Stock storage: corrections, brew edit/delete, backup and catalog isolation passed');

// Exercise the real export path and inspect the downloadable backup payload.
let exportedBlob, clickedDownload;
const savedDocument=globalThis.document;
const savedCreateURL=URL.createObjectURL, savedRevokeURL=URL.revokeObjectURL;
URL.createObjectURL=blob=>{exportedBlob=blob;return 'blob:qa-backup'};
URL.revokeObjectURL=()=>{};
globalThis.document={createElement:tag=>{assert.equal(tag,'a');return {click(){clickedDownload={href:this.href,download:this.download}}}}};
try{
 await exportBackup();
 assert.equal(clickedDownload.href,'blob:qa-backup');
 assert.match(clickedDownload.download,/^beanlet-\d{4}-\d{2}-\d{2}\.json$/);
 const payload=JSON.parse(await exportedBlob.text());
 const current=await localApi('/api/journal');
 assert.ok(payload.exportedAt);
 assert.deepEqual(payload.catalog.filter(b=>!payload.hiddenCatalog.includes(b.id)),JSON.parse(JSON.stringify(current.catalog.filter(b=>!b.id.startsWith('hydrangea-')))));
 assert.ok(!payload.catalog.some(b=>b.id.startsWith('hydrangea-')),'built-in catalog stays bundled in app');
 for(const key of ['beans','brews','tasted','favorites','hiddenCatalog'])assert.deepEqual(payload[key],JSON.parse(JSON.stringify(current[key])),key+' is preserved in export');
 assert.equal(payload.beans.find(b=>b.id==='photo-bean').photo,photo);
 assert.equal(payload.beans.find(b=>b.id===stockBag).stockAdjustment,-15);
 assert.equal(await importBackup(new File([JSON.stringify(payload)],'roundtrip.json')),0);
 console.log('Backup export: real payload, photo, stock, favorites and idempotent reimport passed');
}finally{globalThis.document=savedDocument;URL.createObjectURL=savedCreateURL;URL.revokeObjectURL=savedRevokeURL}
