"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import {Film,Play,Share2,X} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {reelStickerLayout} from '@/lib/sticker-layout';
import {alphaBounds,type PixelBounds} from '@/lib/image-bounds';
import {useI18n} from '@/lib/i18n';

type ReelPhoto={id:string;src:string;cutout?:boolean};
function loadImage(src:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('image'));image.src=src})}
// Visible part of a cutout sticker, so its size on the Reel is measured by the coffee itself, not the transparent margin.
function opaqueBounds(image:HTMLImageElement):PixelBounds{const full={x:0,y:0,width:image.naturalWidth,height:image.naturalHeight},scale=Math.min(1,160/Math.max(full.width,full.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(full.width*scale));canvas.height=Math.max(1,Math.round(full.height*scale));const ctx=canvas.getContext('2d');if(!ctx)return full;ctx.drawImage(image,0,0,canvas.width,canvas.height);let b:PixelBounds|null=null;try{b=alphaBounds(ctx.getImageData(0,0,canvas.width,canvas.height).data,canvas.width,canvas.height,24)}catch{return full}return b?{x:b.x/scale,y:b.y/scale,width:b.width/scale,height:b.height/scale}:full}
// Brisk rhythm: one sticker every ≤0.32s (faster when there are many, so all land within 4.2s); landings overlap, then a 1.1s hold.
const reelLead=120,reelLand=560,reelHold=1100,reelW=720,reelH=1280;
function reelStep(count:number){return Math.min(320,4200/Math.max(1,count))}
// Each sticker is drawn once, shadow included, so a frame only blits bitmaps: live shadow blur on big stickers dropped frames.
type Sprite={canvas:HTMLCanvasElement;w:number;h:number};
function makeSprite(image:HTMLImageElement,crop:PixelBounds,cutout:boolean|undefined,dw:number,dh:number):Sprite{const pad=44,res=1.35,w=dw+pad*2,h=dh+pad*2,canvas=document.createElement('canvas');canvas.width=Math.ceil(w*res);canvas.height=Math.ceil(h*res);const ctx=canvas.getContext('2d')!;ctx.scale(res,res);ctx.translate(w/2,h/2);ctx.shadowColor='rgba(71,80,107,.26)';ctx.shadowBlur=24;ctx.shadowOffsetY=10;if(!cutout){ctx.fillStyle='#fff';roundedRect(ctx,-dw/2-10,-dh/2-10,dw+20,dh+20,Math.min(dw,dh)*.18);ctx.fill();ctx.shadowColor='transparent';roundedRect(ctx,-dw/2,-dh/2,dw,dh,Math.min(dw,dh)*.16);ctx.clip()}ctx.drawImage(image,crop.x,crop.y,crop.width,crop.height,-dw/2,-dh/2,dw,dh);return {canvas,w,h}}
function reelLength(count:number){return reelLead+reelStep(count)*Math.max(0,count-1)+reelLand+reelHold}
function roundedRect(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.closePath()}
function drawReelTitle(ctx:CanvasRenderingContext2D,w:number,month:string){const title='BEANLET',margin=16;ctx.save();ctx.font='700 126px "Bodoni 72",Didot,"Times New Roman",serif';ctx.textBaseline='top';ctx.fillStyle='rgba(91,62,48,.46)';const measured=Math.max(1,ctx.measureText(title).width),target=w-margin*2;ctx.translate(margin,10);ctx.scale(target/measured,1);ctx.fillText(title,0,0);ctx.restore();ctx.save();ctx.font='600 28px Arial,sans-serif';ctx.textAlign='right';ctx.textBaseline='top';ctx.fillStyle='rgba(91,62,48,.52)';ctx.fillText(month.toUpperCase(),w-18,142);ctx.restore()}

export function CoffeeReel({photos,month,fullButton=false}:{photos:ReelPhoto[];month:string;fullButton?:boolean}){
 const {t}=useI18n(),photoKey=photos.map(photo=>photo.id).join('|'),reelDuration=reelLength(photos.length),canvasRef=useRef<HTMLCanvasElement>(null),spritesRef=useRef<Sprite[]>([]),animationRef=useRef(0),[open,setOpen]=useState(false),[playing,setPlaying]=useState(false),[generating,setGenerating]=useState(false),[error,setError]=useState(''),layout=useMemo(()=>reelStickerLayout(photos.map(photo=>photo.id)),[photoKey]);
 function draw(progress:number){const canvas=canvasRef.current,ctx=canvas?.getContext('2d');if(!canvas||!ctx)return;const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const gradient=ctx.createLinearGradient(0,0,w,h);gradient.addColorStop(0,'#f7f5f1');gradient.addColorStop(.52,'#eeeae5');gradient.addColorStop(1,'#e6e0dc');ctx.fillStyle=gradient;ctx.fillRect(0,0,w,h);
  // The whole pile drifts slowly closer, so the frame never sits still; each sticker drops in large, springs past its size and settles, later ones on top.
  const time=progress*reelDuration,step=reelStep(photos.length),push=1+.05*(.5-.5*Math.cos(Math.PI*progress));ctx.save();ctx.translate(w/2,h*.56);ctx.scale(push,push);ctx.translate(-w/2,-h*.56);
  spritesRef.current.forEach((sprite,index)=>{const local=(time-reelLead-index*step)/reelLand,place=layout[index];if(local<=0||!place)return;const p=Math.min(1,local),spring=p<1?Math.exp(-5.5*p)*Math.cos(8.5*p):0,scale=1+.3*spring,lift=-26*Math.pow(1-p,3);ctx.save();ctx.globalAlpha=Math.min(1,p*5);ctx.translate(w*place.x/100,h*place.y/100+lift);ctx.rotate((place.rotation+9*spring)*Math.PI/180);ctx.scale(scale,scale);ctx.drawImage(sprite.canvas,-sprite.w/2,-sprite.h/2,sprite.w,sprite.h);ctx.restore()});
  ctx.restore();ctx.globalAlpha=1;drawReelTitle(ctx,w,month)}
 async function prepare(){try{const images=await Promise.all(photos.map(photo=>loadImage(photo.src)));spritesRef.current=images.map((image,index)=>{const crop=photos[index].cutout?opaqueBounds(image):{x:0,y:0,width:image.naturalWidth,height:image.naturalHeight},size=Math.min(reelW*.9,reelW*(layout[index]?.size||50)/100),ratio=Math.min(1.22,Math.max(.8,crop.height/crop.width));return makeSprite(image,crop,photos[index].cutout,size,size*ratio)});draw(1)}catch{setError(t('有照片暂时无法读取'))}}
 function preview(){cancelAnimationFrame(animationRef.current);setPlaying(true);const started=performance.now();const frame=(now:number)=>{const progress=Math.min(1,(now-started)/reelDuration);draw(progress);if(progress<1)animationRef.current=requestAnimationFrame(frame);else setPlaying(false)};animationRef.current=requestAnimationFrame(frame)}
 async function exportReel(){const canvas=canvasRef.current;if(!canvas||generating)return;setGenerating(true);setError('');let stream:MediaStream|undefined;try{if(!canvas.captureStream||typeof MediaRecorder==='undefined')throw Error(t('这台设备暂不支持生成视频'));await prepare();stream=canvas.captureStream(30);const types=['video/mp4;codecs=h264','video/mp4','video/webm;codecs=vp9','video/webm'],mimeType=types.find(type=>MediaRecorder.isTypeSupported(type))||'';const recorder=new MediaRecorder(stream,mimeType?{mimeType,videoBitsPerSecond:5_000_000}:undefined),chunks:Blob[]=[];recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};const done=new Promise<Blob>((resolve,reject)=>{recorder.onerror=()=>reject(Error(t('视频生成失败，请再试一次')));recorder.onstop=()=>resolve(new Blob(chunks,{type:recorder.mimeType||'video/mp4'}))});recorder.start(250);const started=performance.now();await new Promise<void>(resolve=>{const frame=(now:number)=>{const progress=Math.min(1,(now-started)/reelDuration);draw(progress);if(progress<1)requestAnimationFrame(frame);else resolve()};requestAnimationFrame(frame)});recorder.stop();const blob=await done,extension=blob.type.includes('webm')?'webm':'mp4',name=`beanlet-${month.replace(/\D/g,'-').replace(/^-|-$/g,'')||'reel'}.${extension}`;if((globalThis as any).Capacitor?.isNativePlatform?.()){const {shareNativeVideo}=await import('@/lib/native-video');await shareNativeVideo(blob,name)}else{const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}catch(cause){const message=(cause as Error)?.message||'';if(!/cancel/i.test(message))setError(message)}finally{stream?.getTracks().forEach(track=>track.stop());setGenerating(false);draw(1)}}
 // Closing the dialog or switching between month and year stops a running preview; clear its flag too, or Preview stays disabled.
 useEffect(()=>{if(open)prepare();return()=>{cancelAnimationFrame(animationRef.current);setPlaying(false)}},[open,photoKey]);
 return <><button type="button" className={fullButton?'month-share-button':'reel-entry'} aria-label={t('生成 Reel')} disabled={!photos.length} onClick={()=>setOpen(true)}><Film size={18}/>{fullButton&&<span>{t('生成 Reel')}</span>}</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="reel-dialog" showCloseButton={false}><header className="reel-dialog-heading"><button className="icon-button" onClick={()=>setOpen(false)} aria-label={t('关闭')}><X size={20}/></button><DialogTitle>Reel</DialogTitle><span/></header><DialogDescription className="sr-only">{t('用这个月的咖啡贴纸生成竖屏短片')}</DialogDescription><canvas ref={canvasRef} width={720} height={1280} className="reel-canvas"/><div className="reel-actions"><button className="secondary" disabled={playing||generating} onClick={preview}><Play size={17}/>{t('预览')}</button><button className="primary" disabled={generating} onClick={exportReel}><Share2 size={17}/>{generating?t('正在生成…'):t('生成并分享')}</button></div>{error&&<p className="form-error">{error}</p>}</DialogContent></Dialog></>
}
