"use client";
import {useEffect,useRef,useState} from 'react';
import {Film,Play,Share2,X} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {reelStickerPlacement} from '@/lib/sticker-layout';
import {useI18n} from '@/lib/i18n';

type ReelPhoto={id:string;src:string;cutout?:boolean};
function loadImage(src:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('image'));image.src=src})}
function roundedRect(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.closePath()}
function drawReelTitle(ctx:CanvasRenderingContext2D,w:number,month:string){const title='BEANLET',margin=16;ctx.save();ctx.font='700 126px "Bodoni 72",Didot,"Times New Roman",serif';ctx.textBaseline='top';ctx.fillStyle='rgba(91,62,48,.46)';const measured=Math.max(1,ctx.measureText(title).width),target=w-margin*2;ctx.translate(margin,10);ctx.scale(target/measured,1);ctx.fillText(title,0,0);ctx.restore();ctx.save();ctx.font='600 28px Arial,sans-serif';ctx.textAlign='right';ctx.textBaseline='top';ctx.fillStyle='rgba(91,62,48,.52)';ctx.fillText(month.toUpperCase(),w-18,142);ctx.restore()}

export function CoffeeReel({photos,month,fullButton=false}:{photos:ReelPhoto[];month:string;fullButton?:boolean}){
 const {t}=useI18n(),photoKey=photos.map(photo=>photo.id).join('|'),reelDuration=Math.min(16000,8000+photos.length*400),canvasRef=useRef<HTMLCanvasElement>(null),imagesRef=useRef<HTMLImageElement[]>([]),animationRef=useRef(0),[open,setOpen]=useState(false),[playing,setPlaying]=useState(false),[generating,setGenerating]=useState(false),[error,setError]=useState('');
 function draw(progress:number){const canvas=canvasRef.current,ctx=canvas?.getContext('2d');if(!canvas||!ctx)return;const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const gradient=ctx.createLinearGradient(0,0,w,h);gradient.addColorStop(0,'#f7f5f1');gradient.addColorStop(.52,'#eeeae5');gradient.addColorStop(1,'#e6e0dc');ctx.fillStyle=gradient;ctx.fillRect(0,0,w,h);drawReelTitle(ctx,w,month);
  imagesRef.current.forEach((image,index)=>{const entrance=Math.max(0,Math.min(1,(progress-index/Math.max(1,photos.length)*.62)/.16)),ease=1-Math.pow(1-entrance,3);if(!ease)return;const place=reelStickerPlacement(photos[index].id,index,photos.length),size=Math.min(w*.68,w*place.size/100),ratio=Math.min(1.22,Math.max(.8,image.naturalHeight/image.naturalWidth)),dw=size,dh=size*ratio,targetX=w*place.x/100,targetY=h*place.y/100,cx=Math.max(dw*.42,Math.min(w-dw*.42,targetX)),cy=Math.max(174+dh*.42,Math.min(h-dh*.42,targetY)),settle=Math.sin(progress*Math.PI*2+index)*3*(1-progress);ctx.save();ctx.translate(cx,cy+settle);ctx.rotate(place.rotation*Math.PI/180);ctx.scale(.58+.42*ease,.58+.42*ease);ctx.globalAlpha=ease;if(!photos[index].cutout){ctx.fillStyle='#fff';ctx.shadowColor='#47506b35';ctx.shadowBlur=18;ctx.shadowOffsetY=8;roundedRect(ctx,-dw/2-8,-dh/2-8,dw+16,dh+16,Math.min(dw,dh)*.18);ctx.fill();ctx.shadowColor='transparent';roundedRect(ctx,-dw/2,-dh/2,dw,dh,Math.min(dw,dh)*.16);ctx.clip()}ctx.drawImage(image,-dw/2,-dh/2,dw,dh);ctx.restore()});ctx.globalAlpha=1}
 async function prepare(){try{imagesRef.current=await Promise.all(photos.map(photo=>loadImage(photo.src)));draw(1)}catch{setError(t('有照片暂时无法读取'))}}
 function preview(){cancelAnimationFrame(animationRef.current);setPlaying(true);const started=performance.now();const frame=(now:number)=>{const progress=Math.min(1,(now-started)/reelDuration);draw(progress);if(progress<1)animationRef.current=requestAnimationFrame(frame);else setPlaying(false)};animationRef.current=requestAnimationFrame(frame)}
 async function exportReel(){const canvas=canvasRef.current;if(!canvas||generating)return;setGenerating(true);setError('');let stream:MediaStream|undefined;try{if(!canvas.captureStream||typeof MediaRecorder==='undefined')throw Error(t('这台设备暂不支持生成视频'));await prepare();stream=canvas.captureStream(30);const types=['video/mp4;codecs=h264','video/mp4','video/webm;codecs=vp9','video/webm'],mimeType=types.find(type=>MediaRecorder.isTypeSupported(type))||'';const recorder=new MediaRecorder(stream,mimeType?{mimeType,videoBitsPerSecond:5_000_000}:undefined),chunks:Blob[]=[];recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};const done=new Promise<Blob>((resolve,reject)=>{recorder.onerror=()=>reject(Error(t('视频生成失败，请再试一次')));recorder.onstop=()=>resolve(new Blob(chunks,{type:recorder.mimeType||'video/mp4'}))});recorder.start(250);const started=performance.now();await new Promise<void>(resolve=>{const frame=(now:number)=>{const progress=Math.min(1,(now-started)/reelDuration);draw(progress);if(progress<1)requestAnimationFrame(frame);else resolve()};requestAnimationFrame(frame)});recorder.stop();const blob=await done,extension=blob.type.includes('webm')?'webm':'mp4',name=`beanlet-${month.replace(/\D/g,'-').replace(/^-|-$/g,'')||'reel'}.${extension}`;if((globalThis as any).Capacitor?.isNativePlatform?.()){const {shareNativeVideo}=await import('@/lib/native-video');await shareNativeVideo(blob,name)}else{const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}catch(cause){setError((cause as Error).message)}finally{stream?.getTracks().forEach(track=>track.stop());setGenerating(false);draw(1)}}
 useEffect(()=>{if(open)prepare();return()=>cancelAnimationFrame(animationRef.current)},[open,photoKey]);
 return <><button type="button" className={fullButton?'month-share-button':'reel-entry'} aria-label={t('生成 Reel')} disabled={!photos.length} onClick={()=>setOpen(true)}><Film size={18}/>{fullButton&&<span>{t('生成 Reel')}</span>}</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="reel-dialog" showCloseButton={false}><header className="reel-dialog-heading"><button className="icon-button" onClick={()=>setOpen(false)} aria-label={t('关闭')}><X size={20}/></button><DialogTitle>Reel</DialogTitle><span/></header><DialogDescription className="sr-only">{t('用这个月的咖啡贴纸生成竖屏短片')}</DialogDescription><canvas ref={canvasRef} width={720} height={1280} className="reel-canvas"/><div className="reel-actions"><button className="secondary" disabled={playing||generating} onClick={preview}><Play size={17}/>{t('预览')}</button><button className="primary" disabled={generating} onClick={exportReel}><Share2 size={17}/>{generating?t('正在生成…'):t('生成并分享')}</button></div>{error&&<p className="form-error">{error}</p>}</DialogContent></Dialog></>
}
