'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {Timer,ArrowLeft,Play,Pause,RotateCcw} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {useI18n} from '@/lib/i18n';
import {navigationFeedback} from '@/lib/haptic-feedback';
import {pourRecipes,pourPlan,pourStepIndex,timerSeconds,timerText} from '@/lib/pour-recipes';
export type PourResult={beanId?:string;dose:number;water:number;temp?:number;time:string;grind:string;method:string};
export function PourTimer({dose,onComplete,beans,onOpenChange}:{dose:number;onComplete:(result:PourResult)=>void;beans?:{id:string;name:string;art:ReactNode}[];onOpenChange?:(open:boolean)=>void}){
 const {language}=useI18n(),en=language==='en',say=(zh:string,english:string)=>en?english:zh;
 const [beanId,setBeanId]=useState('');
 const [open,setOpen]=useState(false),[recipeId,setRecipeId]=useState('basic'),[grams,setGrams]=useState('15');
 const [started,setStarted]=useState<number|null>(null),[accumulated,setAccumulated]=useState(0),[now,setNow]=useState(Date.now()),[finished,setFinished]=useState(false);
 useEffect(()=>{onOpenChange?.(open)},[open,onOpenChange]);
 const selected=beans?.find(b=>b.id===beanId),canBrew=!beans||!!selected;
 const lastStep=useRef(-1),recipe=pourRecipes.find(r=>r.id===recipeId)!,valid=Number.isFinite(Number(grams))&&Number(grams)>=1&&Number(grams)<=60;
 const plan=pourPlan(recipe,valid?Number(grams):15),seconds=timerSeconds(accumulated,started,now),index=pourStepIndex(recipe,seconds),step=plan.steps[index],running=started!==null,locked=running||accumulated>0||finished;
 useEffect(()=>{if(!running)return;const update=()=>setNow(Date.now());const id=setInterval(update,200);document.addEventListener('visibilitychange',update);return()=>{clearInterval(id);document.removeEventListener('visibilitychange',update)}},[running]);
 useEffect(()=>{if(running&&index!==lastStep.current){lastStep.current=index;navigationFeedback()}},[index,running]);
 useEffect(()=>{if(!running)return;let disposed=false;let lock:WakeLockSentinel|undefined;const acquire=async()=>{if(document.visibilityState!=='visible')return;try{const next=await navigator.wakeLock?.request('screen');if(disposed)void next?.release();else lock=next}catch{}};void acquire();document.addEventListener('visibilitychange',acquire);return()=>{disposed=true;void lock?.release();document.removeEventListener('visibilitychange',acquire)}},[running]);
 function reset(){setStarted(null);setAccumulated(0);setNow(Date.now());setFinished(false);lastStep.current=-1}
 function pause(){const end=Date.now();setAccumulated(v=>v+(started===null?0:end-started));setStarted(null);setNow(end)}
 function begin(){const start=Date.now();setNow(start);setStarted(start)}
 function finish(){pause();setFinished(true)}
 return <><button type="button" className={beans?'pour-timer-shortcut':'pour-timer-entry'} aria-label={say('快捷手冲计时','Quick brew timer')} title={say('快捷手冲计时','Quick brew timer')} onClick={()=>{reset();setBeanId(beans?.find(b=>b.id===beanId)?.id||beans?.[0]?.id||'');setGrams(String(dose>0&&dose<=60?dose:15));setOpen(true)}}>{beans?<><span className="sticker sticker-dripper" aria-hidden="true"/><Timer className="shortcut-clock" size={17} aria-hidden="true"/></>:<><Timer size={18}/>{say('跟着冲 · 计时与注水','Brew along · timer & pours')}</>}</button><Dialog open={open} onOpenChange={value=>{if(!running)setOpen(value)}}><DialogContent className="pour-timer-dialog" showCloseButton={false} onEscapeKeyDown={event=>{if(running)event.preventDefault()}} onPointerDownOutside={event=>{if(running)event.preventDefault()}}>
 <div className="pour-timer-nav"><button type="button" className="icon-button" aria-label={say('返回','Back')} disabled={running} onClick={()=>setOpen(false)}><ArrowLeft size={20}/></button><DialogTitle>{say('慢慢冲一杯','A little brewing time')}</DialogTitle><span className="sticker sticker-dripper" aria-hidden="true"/></div>
 <DialogDescription className="pour-timer-caption">{say('水量为目标值，请配合咖啡秤。冲煮时保持页面打开。','Water amounts are targets; use a scale. Keep this screen open while brewing.')}</DialogDescription>
 <div className="pour-timer-scroll">{beans&&<label className="field pour-timer-bean">{say('今天冲哪包？','Choose your beans')}<Select disabled={locked||!beans.length} value={beanId} onValueChange={setBeanId}><SelectTrigger className="choice brew-coffee-trigger" aria-label={say('今天冲哪包？','Choose your beans')}><SelectValue placeholder={beans.length?say('选择一包豆子','Choose a bag'):say('先在豆仓添加一包豆子','Add a bag to your shelf first')}/></SelectTrigger><SelectContent className="brew-coffee-menu" position="popper">{beans.map(bean=><SelectItem className="brew-coffee-option" key={bean.id} value={bean.id} textValue={bean.name}><span className="brew-coffee-choice">{bean.art}<span className="brew-coffee-name">{bean.name}</span></span></SelectItem>)}</SelectContent></Select></label>}<div className="pour-timer-setup"><label className="field">{say('冲法','Recipe')}<select disabled={locked} value={recipeId} onChange={e=>setRecipeId(e.target.value)}>{pourRecipes.map(r=><option key={r.id} value={r.id}>{en?r.en:r.zh}</option>)}</select></label><label className="field">{say('粉量 · g','Coffee · g')}<input disabled={locked} type="number" min="1" max="60" step="0.1" value={grams} onChange={e=>setGrams(e.target.value)}/></label></div>
 {!valid&&<p role="alert" className="error">{say('粉量请输入 1–60 g','Enter 1–60 g of coffee')}</p>}
 <div className="pour-timer-facts"><span>{say('总水量','Total water')} {plan.total} g</span><span>1 : {recipe.ratio.toFixed(1)}</span>{recipe.temp&&<span>{recipe.temp} °C</span>}</div>
 <section className="pour-timer-focus">
 <div className="pour-timer-clock"><span>{finished?say('冲煮完成','Brew finished'):running?say('已用时','Elapsed'):accumulated?say('已暂停','Paused'):say('准备开始','Ready to brew')}</span><strong role="timer" aria-label={say('冲煮计时','Brew timer')}>{timerText(seconds)}</strong></div>
 <div className="pour-stage-track" aria-label={say('注水阶段','Pour stages')}>{plan.steps.map((s,i)=><span key={s.at} data-past={i<index} aria-current={i===index?'step':undefined}/>)}</div>
 {finished?<div className="pour-timer-target"><span>{say('这一杯，慢慢享用','Enjoy your cup')}</span><strong>{Number(grams)} g <small>{say('咖啡粉','coffee')}</small> · {plan.total} g <small>{say('目标水量','target water')}</small></strong></div>:<>
 <div className="pour-timer-target" aria-live="polite"><span>{say('第','Pour')} {index+1} / {plan.steps.length} {say('段','')} · {index===0?say('闷蒸','Bloom'):say('注水','Pour')}</span><strong><small>{say('累计注到','Pour up to')}</small><b>{step.target}</b><small>g</small></strong><span>{say('本段加','Add')} {step.amount} g · {en?step.en:step.zh}</span></div>
 <div className="pour-timer-next">{plan.steps[index+1]?<><span>{say('下一段','Next pour')} · {plan.steps[index+1].target} g</span><strong>{!locked?timerText(plan.steps[index+1].at):`${timerText(Math.max(0,plan.steps[index+1].at-seconds))} ${say('后','to go')}`}</strong></>:<span>{seconds>=recipe.seconds?say('滴滤结束后，点「冲好了」','Tap Finished when drained'):say('注水完成后等待滴滤','Let drain after pouring')} · {say('参考','Aim for')} {timerText(recipe.seconds)}</span>}</div></>}
 </section>
 <details className="pour-plan"><summary>{say('完整注水计划','Full pour plan')}<span>{plan.steps.length} {say('段','pours')} · {timerText(recipe.seconds)}</span></summary><ol className="pour-timer-steps">{plan.steps.map((s,i)=><li key={s.at} aria-current={!finished&&i===index?'step':undefined}><time>{timerText(s.at)}</time><span>{i===0?say('闷蒸','Bloom'):say('注水','Pour')}</span><strong>{s.target} g</strong></li>)}</ol><p>{say('表内水量为累计目标 · 研磨','Cumulative water targets · Grind')} {en?recipe.grindEn:recipe.grindZh}</p></details>
 <details className="pour-timer-notes"><summary>{say('冲法小贴士','Recipe tips')}</summary><p>{en?recipe.noteEn:recipe.noteZh}</p><p>{say('按粉量等比例换算水量，时间不同比例缩放；滴滤速度和口味优先。','Water scales with your dose; timing does not. Follow drainage and taste.')}</p>{recipe.source&&<a href={recipe.source} target="_blank" rel="noreferrer">{say('查看原配方 ↗','Original recipe ↗')}</a>}</details></div>
 <div className="pour-timer-actions">{finished?<><button type="button" className="secondary" onClick={reset}><RotateCcw size={16}/>{say('重来','Reset')}</button><button type="button" className="primary" onClick={()=>{onComplete({beanId:beans?beanId:undefined,dose:Number(grams),water:plan.total,temp:recipe.temp,time:timerText(seconds),grind:en?recipe.grindEn:recipe.grindZh,method:en?recipe.en:recipe.zh});setOpen(false)}}>{say('带入记录','Use in record')}</button></>:<><button type="button" className="primary" disabled={!valid||!canBrew} onClick={running?pause:begin}>{running?<Pause size={17}/>:<Play size={17}/>} {running?say('暂停','Pause'):accumulated?say('继续','Resume'):say('开始','Start')}</button>{locked&&<button type="button" className="secondary" onClick={finish}>{say('冲好了','Finished')}</button>}{!running&&locked&&<button type="button" className="icon-button" aria-label={say('重新计时','Reset timer')} onClick={reset}><RotateCcw size={17}/></button>}</>}</div>
 </DialogContent></Dialog></>;
}
