import {stickerPlacement} from './sticker-layout';
import {drawDrunkBag,type DrunkBag} from './monthly-report-image';

type AnnualPhoto={id:string;src:string;cutout?:boolean};
type AnnualDay={date:string;cups:number};
type AnnualReportInput={language:'zh'|'en';year:number;cups:number;pourOvers:number;milks:number;days:AnnualDay[];months:{label:string;cups:number}[];drunkBags:DrunkBag[];photos:AnnualPhoto[]};

function loadImage(src:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('image'));image.src=src})}
function roundRect(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.closePath()}
function card(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r=34){ctx.fillStyle='rgba(255,255,255,.58)';roundRect(ctx,x,y,w,h,r);ctx.fill()}
function drawBean(ctx:CanvasRenderingContext2D,x:number,y:number,size:number,rotation:number,color:string){ctx.save();ctx.translate(x,y);ctx.rotate(rotation);ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(0,0,size*.43,size*.62,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(92,67,57,.28)';ctx.lineWidth=Math.max(2,size*.035);ctx.beginPath();ctx.moveTo(-size*.08,-size*.48);ctx.bezierCurveTo(size*.16,-size*.20,-size*.18,size*.18,size*.08,size*.48);ctx.stroke();ctx.restore()}

export async function createAnnualReportImage(input:AnnualReportInput){
 await document.fonts?.ready;
 const loaded=(await Promise.all(input.photos.slice(0,24).map(async photo=>{try{return {photo,image:await loadImage(photo.src)}}catch{return null}}))).filter((item):item is {photo:AnnualPhoto;image:HTMLImageElement}=>!!item),reportHeight=1920;
 const bagImages=new Map((await Promise.all(input.drunkBags.map(async bag=>{try{return [bag.id,await loadImage(bag.art)] as const}catch{return null}}))).filter((item):item is readonly [string,HTMLImageElement]=>!!item));
 const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=reportHeight;const ctx=canvas.getContext('2d');if(!ctx)throw Error('canvas');
 const gradient=ctx.createLinearGradient(0,0,1080,reportHeight);gradient.addColorStop(0,'#f8f5f0');gradient.addColorStop(.55,'#f1edf0');gradient.addColorStop(1,'#e7e8f1');ctx.fillStyle=gradient;ctx.fillRect(0,0,1080,reportHeight);
 ctx.fillStyle='rgba(119,103,135,.075)';ctx.beginPath();ctx.ellipse(970,300,270,390,-.35,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(191,151,142,.07)';ctx.beginPath();ctx.ellipse(70,reportHeight-220,300,280,.45,0,Math.PI*2);ctx.fill();
 const serif='"Bodoni 72",Didot,"Times New Roman",serif',ui='"LXGW WenKai Lite","Klee One","Songti SC",serif';ctx.textBaseline='top';ctx.fillStyle='rgba(86,62,52,.72)';ctx.font=`700 154px ${serif}`;const title='BEANLET',titleWidth=ctx.measureText(title).width;ctx.save();ctx.translate(48,25);ctx.scale(984/titleWidth,1);ctx.fillText(title,0,0);ctx.restore();ctx.textAlign='right';ctx.font='600 30px Arial,sans-serif';ctx.fillStyle='rgba(86,62,52,.58)';ctx.fillText(String(input.year),1030,185);ctx.textAlign='left';

 // GitHub-style full-year brew heatmap.
 card(ctx,48,245,984,430,38);const square=12,gap=5,step=square+gap,startX=105,startY=323,maxCups=Math.max(1,...input.days.map(day=>day.cups)),firstDay=new Date(input.year,0,1).getDay(),weekdays=input.language==='en'?['S','','T','','T','','S']:['日','','二','','四','','六'];ctx.fillStyle='rgba(82,91,120,.4)';ctx.font=`400 16px ${ui}`;ctx.textAlign='right';ctx.textBaseline='middle';weekdays.forEach((day,row)=>day&&ctx.fillText(day,startX-17,startY+row*step+square/2));
 const monthStarts=Array.from({length:12},(_,month)=>{const dayIndex=Math.round((new Date(input.year,month,1).getTime()-new Date(input.year,0,1).getTime())/86400000),week=Math.floor((firstDay+dayIndex)/7);return {month,week}});ctx.textAlign='left';ctx.textBaseline='top';ctx.font='500 14px Arial,sans-serif';ctx.fillStyle='rgba(82,91,120,.42)';monthStarts.forEach(({month,week})=>ctx.fillText(String(month+1).padStart(2,'0'),startX+week*step,startY-28));
 input.days.forEach((day,index)=>{const cell=firstDay+index,week=Math.floor(cell/7),row=cell%7,x=startX+week*step,y=startY+row*step,intensity=day.cups?(.28+.66*day.cups/maxCups):.07;ctx.fillStyle=`rgba(126,141,190,${intensity})`;roundRect(ctx,x,y,square,square,3);ctx.fill()});ctx.textAlign='left';ctx.textBaseline='top';ctx.fillStyle='rgba(82,91,120,.48)';ctx.font='500 17px Arial,sans-serif';ctx.fillText(input.language==='en'?'LESS':'少',745,500);[.08,.28,.48,.68,.9].forEach((alpha,index)=>{ctx.fillStyle=`rgba(126,141,190,${alpha})`;roundRect(ctx,800+index*27,498,18,18,4);ctx.fill()});ctx.fillStyle='rgba(82,91,120,.48)';ctx.fillText(input.language==='en'?'MORE':'多',948,500);

 // Annual photo wall; keep the same visual area even before photos are added.
 card(ctx,48,700,984,550,38);if(loaded.length){const columns=loaded.length<=3?loaded.length:loaded.length<=8?4:loaded.length<=15?5:6,rows=Math.ceil(loaded.length/columns),area={x:82,y:732,w:916,h:482},cellW=area.w/columns,cellH=area.h/rows;loaded.forEach(({photo,image},index)=>{const place=stickerPlacement(photo.id,index,loaded.length,false),row=Math.floor(index/columns),column=index%columns,items=Math.min(columns,loaded.length-row*columns),offset=(columns-items)*cellW/2,ratio=Math.min(1.2,Math.max(.82,image.naturalHeight/image.naturalWidth)),size=Math.min(218,Math.max(88,Math.min(cellW*1.08,cellH*1.04/ratio))),dw=size,dh=size*ratio,cx=area.x+offset+(column+.5)*cellW,cy=area.y+(row+.5)*cellH;ctx.save();ctx.translate(cx,cy);ctx.rotate(place.rotation*.6*Math.PI/180);if(!photo.cutout){ctx.fillStyle='rgba(255,255,255,.94)';ctx.shadowColor='rgba(69,60,78,.13)';ctx.shadowBlur=20;ctx.shadowOffsetY=7;roundRect(ctx,-dw/2-7,-dh/2-7,dw+14,dh+14,28);ctx.fill();ctx.shadowColor='transparent';roundRect(ctx,-dw/2,-dh/2,dw,dh,23);ctx.clip()}else{ctx.shadowColor='rgba(69,60,78,.11)';ctx.shadowBlur=14;ctx.shadowOffsetY=6}ctx.drawImage(image,-dw/2,-dh/2,dw,dh);ctx.restore()})}else{const colors=['#d8c7d7','#c8d5e8','#e7c8bd','#c9d9cf','#e7d9b9'];for(let i=0;i<13;i++){const angle=i*2.399,r=55+Math.sqrt(i)*92;drawBean(ctx,540+Math.cos(angle)*r,990+Math.sin(angle)*r*.57,62+(i%4)*9,angle*.18,colors[i%colors.length])}}

 // Method split and monthly brew bars.
 card(ctx,48,1275,230,305,34);card(ctx,298,1275,734,305,34);ctx.fillStyle='rgba(82,91,120,.52)';ctx.font=`600 18px ${serif}`;ctx.fillText(input.language==='en'?'METHOD':'冲煮方式',72,1302);ctx.fillText(input.language==='en'?'MONTHLY BREWS':'每月冲煮',326,1302);const total=Math.max(1,input.pourOvers+input.milks),pourAngle=Math.PI*2*input.pourOvers/total,cx=163,cy=1420;ctx.lineWidth=25;ctx.strokeStyle='rgba(203,183,214,.70)';ctx.beginPath();ctx.arc(cx,cy,58,-Math.PI/2,Math.PI*1.5);ctx.stroke();if(input.pourOvers){ctx.strokeStyle='rgba(139,153,198,.88)';ctx.beginPath();ctx.arc(cx,cy,58,-Math.PI/2,-Math.PI/2+pourAngle);ctx.stroke()}ctx.textAlign='center';ctx.fillStyle='#56617f';ctx.font=`600 34px ${ui}`;ctx.fillText(String(input.cups),cx,1397);ctx.font=`400 17px ${ui}`;ctx.fillStyle='#7783a9';ctx.fillText(`${input.language==='en'?'Pour':'手冲'} ${input.pourOvers}`,cx,1502);ctx.fillStyle='#a28eae';ctx.fillText(`${input.language==='en'?'Milk':'奶咖'} ${input.milks}`,cx,1530);ctx.textAlign='left';const graph={x:340,y:1360,w:648,h:148},barMax=Math.max(1,...input.months.map(month=>month.cups)),barStep=graph.w/12,barWidth=26;input.months.forEach((month,index)=>{const height=month.cups?Math.max(8,month.cups/barMax*graph.h):0,x=graph.x+index*barStep+(barStep-barWidth)/2,y=graph.y+graph.h-height;ctx.fillStyle='rgba(133,149,198,.82)';roundRect(ctx,x,y,barWidth,height,8);ctx.fill();ctx.fillStyle='rgba(82,91,120,.48)';ctx.font='500 13px Arial,sans-serif';ctx.textAlign='center';ctx.fillText(month.label,x+barWidth/2,1532)});ctx.textAlign='left';

 // Bags brewed this year, matching the monthly report.
 card(ctx,48,1605,984,250,38);ctx.fillStyle='rgba(82,91,120,.52)';ctx.font=`600 20px ${serif}`;ctx.fillText(input.language==='en'?'BEANS THIS YEAR':'今年喝过',78,1635);if(input.drunkBags.length){const count=input.drunkBags.length,gap=Math.min(12,150/count),available=924-gap*(count-1),bagW=Math.min(88,available/count),bagH=Math.min(132,bagW*1.25),startX=78,y=1687+(132-bagH)/2;input.drunkBags.forEach((bag,index)=>drawDrunkBag(ctx,bag,bagImages.get(bag.id),startX+index*(bagW+gap),y,bagW,bagH,ui))}
 return new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(Error('image')),'image/png'));
}
